// <auto-generated />
using KaraWeb.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaraWeb.Core.Migrations
{
    [DbContext(typeof(KaraWebDbContext))]
    [Migration("20260530074012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KaraWeb.Core.Models.Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("KaraWeb.Core.Models.Songs.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bpm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cover")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Editions")
                        .HasColumnType("TEXT");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gap")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrumental")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedleyEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedleyStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviewStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendition")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Start")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Video")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoGap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vocals")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Warnings")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("KaraWeb.Core.Models.Songs.SongPlayer", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SongId", "Number");

                    b.ToTable("SongPlayers");
                });

            modelBuilder.Entity("KaraWeb.Core.Models.Songs.Song", b =>
                {
                    b.HasOne("KaraWeb.Core.Models.Collections.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("KaraWeb.Core.Models.Songs.SongPlayer", b =>
                {
                    b.HasOne("KaraWeb.Core.Models.Songs.Song", "Song")
                        .WithMany("Players")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraWeb.Core.Models.Songs.Song", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
