# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - uses: actions/setup-node@v4
      with:
          node-version: 21
          
    - name: Restore host dependencies
      run: dotnet restore
      working-directory: Host
    - name: Build host
      run: dotnet build --no-restore
      working-directory: Host
      
    - name: Restore front dependencies
      run: npm install
      working-directory: Front
    - name: Build front
      run: npm run build
      working-directory: Front
